name: Build with pyinstaller than release package

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - run: |
        pwd
        ls -l
        export PYTHONPATH=${pwd}
        docker run -v "${pwd}:/src/" cdrx/pyinstaller-windows:python3 "pyinstaller --onefile crypty.py" 
