name: Build with pyinstaller than release package

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: check environment
      run: |
        python3 --version
        docker --version
        git status
        pwd
        ls -la
        
    - name: package
      uses: action/pyinstaller-windows@main
      with:
        path: ${pwd}
