name: Build with pyinstaller than release package

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: checkout
      uses: actions/checkout@v2
    
    - name: pyinstaller
      run: |
        docker run -v "/home/runner/work/crypty-crypty/crypty-crypty:/src/" cdrx/pyinstaller-windows:python3 "pyinstaller --onefile --windowed crypty.py"
    
    - name: delete last release
      uses: ame-yu/action-delete-latest-release@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: release
      uses: softprops/action-gh-release@v1
      with:
        body: Simple test release on main pushes for learning Github CI.
        tag_name: test
        files: /home/runner/work/crypty-crypty/crypty-crypty/dist/crypty.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
