name: Build with pyinstaller than release package

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    container: 
      image: cdrx/pyinstaller-windows:python3
      options: -v &{pwd}:/src/

    steps:
    - uses: actions/checkout@v2
    - run: pwd
