name: Build with pyinstaller than release package

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
      REPO_PATH: /home/runner/work/crypty-crypty/crypty-crypty
    
    steps:
    - name: checkout
      uses: actions/checkout@v2
    
    - name: pyinstaller
      run: |
        docker run -v "${REPO_PATH}:/src/" cdrx/pyinstaller-windows:python3 "pyinstaller --onefile --windowed crypty.py"
        mkdir ${REPO_PATH}/win
        cp ${REPO_PATH}/dist/crypty.exe ${REPO_PATH}/win/crypty-win.exe
        docker run -v "${REPO_PATH}:/src/" cdrx/pyinstaller-linux:python3 "pyinstaller --onefile --windowed crypty.py"
        mv ${REPO_PATH}/dist/crypty ${REPO_PATH}/dist/crypty-linux
    
    - name: delete last release
      uses: ame-yu/action-delete-latest-release@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: release
      uses: softprops/action-gh-release@v1
      with:
        body: Simple test release on main pushes for learning Github CI.
        tag_name: test
        files: |
          ${REPO_PATH}/win/crypty-win.exe
          ${REPO_PATH}/dist/crypty-linux
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
